name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  check:
    name: Semantic check
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install
        run: yarn --immutable
