name: Publish Package to npmjs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  publish-npm:
    name: release
    runs-on: ubuntu-latest
    needs: [check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          cache: yarn

      - run: yarn --immutable
        if: ${{ steps.release.outputs.release_created }}

      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml

      - run: yarn npm publish --access public
        if: ${{ steps.release.outputs.releases_created }}
